services:
  - type: web
    name: inventory-management
    env: node
    nodeVersion: 16
    buildCommand: cd server && npm install && npm run build
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
    healthCheckPath: / 